import React, { useState, useEffect } from 'react';
import {
    Car, Plus, Trash2, ArrowRight, Info, Check,
    AlertCircle, Loader2, MapPin
} from 'lucide-react';
import type {
    BasicInfoData,
    FlightSelectionData,
    HotelSelectionData,
    TransferSelectionData,
    Transfer,
    TransferVehicle
} from '../../../types/packageSearch.types';

interface Step4Props {
    basicInfo: BasicInfoData | null;
    flights: FlightSelectionData | null;
    hotels: HotelSelectionData[];
    data: TransferSelectionData[];
    onUpdate: (data: TransferSelectionData[]) => void;
    onNext: () => void;
    onBack: () => void;
}

const VEHICLE_TEMPLATES: TransferVehicle[] = [
    {
        id: 'v1',
        name: 'Standard Sedan',
        type: 'sedan',
        capacity: { passengers: 3, luggage: 2 },
        amenities: ['Klima', 'Wi-Fi'],
        image: '',
        price: 25,
        currency: 'EUR'
    },
    {
        id: 'v2',
        name: 'Premium Van',
        type: 'van',
        capacity: { passengers: 7, luggage: 6 },
        amenities: ['Klima', 'Wi-Fi', 'Voda', 'Kožna sedišta'],
        image: '',
        price: 45,
        currency: 'EUR'
    },
    {
        id: 'v3',
        name: 'Minibus',
        type: 'minibus',
        capacity: { passengers: 16, luggage: 15 },
        amenities: ['Klima', 'Mikrofon'],
        image: '',
        price: 120,
        currency: 'EUR'
    }
];

const Step4_TransferSelection: React.FC<Step4Props> = ({
    basicInfo,
    flights,
    hotels,
    data,
    onUpdate,
    onNext,
    onBack
}) => {
    const [transfers, setTransfers] = useState<TransferSelectionData[]>(data || []);
    const [autoGenerated, setAutoGenerated] = useState(false);

    // Auto-generate suggested transfers based on itinerary
    useEffect(() => {
        if (!autoGenerated && basicInfo && hotels.length > 0 && transfers.length === 0) {
            generateSuggestedTransfers();
            setAutoGenerated(true);
        }
    }, [basicInfo, hotels]);

    const generateSuggestedTransfers = () => {
        if (!basicInfo || hotels.length === 0) return;

        const suggested: TransferSelectionData[] = [];
        const firstHotel = hotels[0];
        const lastHotel = hotels[hotels.length - 1];

        // 1. Arrival Airport to First Hotel
        const firstDest = basicInfo.destinations[0];
        suggested.push({
            transfer: {
                id: 't-in',
                type: 'airport_hotel',
                from: `Aerodrom ${firstDest.city} (${firstDest.airportCode || 'APT'})`,
                to: firstHotel.hotel.name,
                distance: 25,
                duration: 45,
                vehicles: VEHICLE_TEMPLATES
            },
            vehicle: VEHICLE_TEMPLATES[0],
            date: firstHotel.checkIn,
            time: '14:00',
            totalPrice: VEHICLE_TEMPLATES[0].price
        });

        // 2. Inter-city transfers or Inter-hotel transfers
        for (let i = 0; i < hotels.length - 1; i++) {
            const current = hotels[i];
            const next = hotels[i + 1];
            suggested.push({
                transfer: {
                    id: `t-inter-${i}`,
                    type: 'inter_city',
                    from: `${current.hotel.name} (${current.hotel.city})`,
                    to: `${next.hotel.name} (${next.hotel.city})`,
                    distance: 120,
                    duration: 90,
                    vehicles: VEHICLE_TEMPLATES
                },
                vehicle: VEHICLE_TEMPLATES[0],
                date: next.checkIn,
                time: '10:00',
                totalPrice: VEHICLE_TEMPLATES[0].price * 4
            });
        }

        // 3. Last Hotel to Departure Airport
        const lastDest = basicInfo.destinations[basicInfo.destinations.length - 1];
        suggested.push({
            transfer: {
                id: 't-out',
                type: 'hotel_airport',
                from: lastHotel.hotel.name,
                to: `Aerodrom ${lastDest.city} (${lastDest.airportCode || 'APT'})`,
                distance: 25,
                duration: 45,
                vehicles: VEHICLE_TEMPLATES
            },
            vehicle: VEHICLE_TEMPLATES[0],
            date: lastHotel.checkOut,
            time: '12:00',
            totalPrice: VEHICLE_TEMPLATES[0].price
        });

        setTransfers(suggested);
        onUpdate(suggested);
    };

    const handleVehicleChange = (transferIdx: number, vehicle: TransferVehicle) => {
        const updated = [...transfers];
        updated[transferIdx] = {
            ...updated[transferIdx],
            vehicle,
            totalPrice: vehicle.price * (updated[transferIdx].transfer.type === 'inter_city' ? 3 : 1)
        };
        setTransfers(updated);
        onUpdate(updated);
    };

    const removeTransfer = (idx: number) => {
        const updated = transfers.filter((_, i) => i !== idx);
        setTransfers(updated);
        onUpdate(updated);
    };

    const addManualTransfer = () => {
        const newTransfer: TransferSelectionData = {
            transfer: {
                id: `t-manual-${Date.now()}`,
                type: 'custom',
                from: 'Nova Lokacija',
                to: 'Nova Lokacija',
                distance: 0,
                duration: 0,
                vehicles: VEHICLE_TEMPLATES
            },
            vehicle: VEHICLE_TEMPLATES[0],
            date: basicInfo?.startDate || '',
            time: '12:00',
            totalPrice: VEHICLE_TEMPLATES[0].price
        };
        const updated = [...transfers, newTransfer];
        setTransfers(updated);
        onUpdate(updated);
    };

    return (
        <div className="step-content">
            <div className="step-header">
                <h2><Car size={24} /> Izbor Transfera</h2>
                <p>Izaberite transfere za vaše putovanje</p>
            </div>

            <div className="transfers-summary">
                <div className="suggested-transfers-header">
                    <h3>Predloženi transferi</h3>
                    <button className="add-manual-btn" onClick={addManualTransfer}>
                        <Plus size={16} /> Dodaj Transfer
                    </button>
                </div>

                {transfers.length > 0 ? (
                    <div className="transfers-list">
                        {transfers.map((item, idx) => (
                            <div key={item.transfer.id} className="transfer-item-card">
                                <div className="transfer-main">
                                    <div className="transfer-type-icon">
                                        <Car size={24} />
                                    </div>
                                    <div className="transfer-route">
                                        <div className="route-names">
                                            <span className="from">{item.transfer.from}</span>
                                            <ArrowRight size={16} />
                                            <span className="to">{item.transfer.to}</span>
                                        </div>
                                        <div className="transfer-meta">
                                            <span>{item.transfer.type.replace('_', ' ')}</span>
                                            <span>•</span>
                                            <span>{item.date} u {item.time}h</span>
                                        </div>
                                    </div>
                                    <div className="transfer-vehicle-select">
                                        <select
                                            value={item.vehicle.id}
                                            onChange={(e) => {
                                                const v = VEHICLE_TEMPLATES.find(v => v.id === e.target.value);
                                                if (v) handleVehicleChange(idx, v);
                                            }}
                                        >
                                            {VEHICLE_TEMPLATES.map(v => (
                                                <option key={v.id} value={v.id}>
                                                    {v.name} ({v.capacity.passengers} os.)
                                                </option>
                                            ))}
                                        </select>
                                    </div>
                                    <div className="transfer-price">
                                        {item.totalPrice.toFixed(2)} €
                                    </div>
                                    <button
                                        className="remove-transfer-btn"
                                        onClick={() => removeTransfer(idx)}
                                    >
                                        <Trash2 size={18} />
                                    </button>
                                </div>
                            </div>
                        ))}
                    </div>
                ) : (
                    <div className="empty-state">
                        <Info size={32} />
                        <p>Niste izabrali nijedan transfer.</p>
                        <button onClick={generateSuggestedTransfers} className="retry-btn">
                            Generiši predloge
                        </button>
                    </div>
                )}
            </div>

        </div>
    );
};

export default Step4_TransferSelection;
