using System;
using System.Collections.Generic;

namespace UOS.Business.PortalTA.DTO
{
	///<summary>
	/// TravelContract Data Transfer Object.
	/// </summary>
	/// <note>
	/// Data transfer objects are used for encapsulation of information carried by a business object, with the difference
	/// of not being directly related to NHibernate session, nor the underlying database representation.
	/// They belong to a class of objects often referred to as POCO (Plain Old C# Object).
	/// If you are encountering this object for the first time, please sift through the following articles
	/// before any coding on your part takes place (note the controversy on its use in our context):
	///		1) https://en.wikipedia.org/wiki/Data_transfer_object
	///		2) http://martinfowler.com/bliki/LocalDTO.html
	///</note>
	public partial class TravelContractDTO
	{
		public long Id { get; set; }
		public int? Version { get; set; }

		#region Generated Properties

		/// <summary>
		/// Contract number defined by travel agency, unique within the same year.
		/// </summary>
		public string Number { get; set; }

		/// <summary>
		/// Contract number unique for travel agency and all years (automatically created by adding year suffix to Number).
		/// </summary>
		public string UniqueNumber { get; set; }

		/// <summary>
		/// Date of the contract. This date is important for finding policy on which passengers should be counted.
		/// </summary>
		public DateTime? ContractDate { get; set; }

		/// <summary>
		/// Number of the certificate generated by the system when contract changed its status to Concluded. This number is used by passengers to check is their travel guarantee valid.
		/// </summary>
		public string TravelGuaranteeCertificateNumber { get; set; }

		/// <summary>
		/// Date and time when certificate number was generated.
		/// </summary>
		public DateTime? TravelGuaranteeCertificateDate { get; set; }

		/// <summary>
		/// Contractor name. First and last name of the person or name of the company.
		/// </summary>
		public string ContractorName { get; set; }

		/// <summary>
		/// Identification number of the contractor.
		/// </summary>
		public string ContractorIdentificationNumber { get; set; }

		/// <summary>
		/// Date of birth of contractor (only in case when contractor is person).
		/// </summary>
		public DateTime? ContractorDateOfBirth { get; set; }

		/// <summary>
		/// Email address of contactor.
		/// </summary>
		public string ContractorEmailAddress { get; set; }

		/// <summary>
		/// Travel start date (departure date).
		/// </summary>
		public DateTime? TravelStartDate { get; set; }

		/// <summary>
		/// Travel end date (date when return from travel).
		/// </summary>
		public DateTime? TravelEndDate { get; set; }

		/// <summary>
		/// Travel departure place.
		/// </summary>
		
		public string DeparturePlace { get; set; }

		/// <summary>
		/// Travel destination place.
		/// </summary>
		
		public string DestinationPlace { get; set; }

		/// <summary>
		/// Travel contract total value in selected currency.
		/// </summary>
		public decimal? TravelContractValueInCurrency { get; set; }

		/// <summary>
		/// Travel contract total value in RSD.
		/// </summary>
		public decimal? TravelContractValueInRSD { get; set; }

		/// <summary>
		/// Total number of passengers on this travel contract. This number is used for counting passengers.
		/// </summary>
		public int? NumberOfPassengers { get; set; }

		/// <summary>
		/// Policy for which this contract is linked. Contract passengers will be counted on this policy.
		/// Id of associated object.
		/// </summary>
		public long? PolicyId { get; set; }


		/// <summary>
		/// Insurance company for this travel contract.
		/// Reference is redundant because it could be reached over policy, but this way permissions check will be faster.
		///
		/// Id of associated object.
		/// </summary>
		public long? InsuranceCompanyId { get; set; }

		/// <summary>
		/// Travel agency of this travel contract.
		/// Reference is redundant because it could be reached over policy, but this way permissions check will be faster.
		///
		/// Id of associated object.
		/// </summary>
		public long? TravelAgencyId { get; set; }

		/// <summary>
		/// Travel departure country.
		/// Id of associated object.
		/// </summary>
		public long? DepartureCountryId { get; set; }

		/// <summary>
		/// Travel destination country.
		/// Id of associated object.
		/// </summary>
		public long? DestinationCountryId { get; set; }

		/// <summary>
		/// Currency for travel contract value.
		/// Id of associated object.
		/// </summary>
		public long? TravelContractValueCurrencyId { get; set; }

		/// <summary>
		/// 
		/// The original contract based on which the this one is created. This is done when original (replaced) contract is canceled by replacing.
		/// The status of the original contract will be set to Canceled in the moment when the first new contract changed its status to Concluded.
		///
		/// Id of associated object.
		/// </summary>
		public long? ReplacedContractId { get; set; }

		/// <summary>
		/// Status of this contract.
		/// Id of associated object.
		/// </summary>
		public long? ContractStatusId { get; set; }

		/// <summary>
		/// Cancellation reason of this contract.
		/// Id of associated object.
		/// </summary>
		public long? CancellationReasonId { get; set; }

		#endregion Generated Properties

		public List<TravelRoutePointDTO> TravelRoutePoints { get; set; }
		public List<PassengerDTO> Passengers { get; set; }
		/// <summary>
		/// Collection of new contracts that have replacing the current contract (only one contract should be in this collection).
		/// The contract is added in this collection in the moment when the original(replaced) contract is canceled by replacing.
		/// When status of the new contract is set to Concluded, the status of the replaced contract will be set to Canceled.
		/// </summary>
		public List<TravelContractDTO> NewContracts { get; set; }
	}
}